In [ ]:
import pandas as pd
import numpy as np

bruto = pd.DataFrame({
    "pedido":    [1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008],
    "descricao": ["Notebook Dell - SP", "mouse logitech - rj", "Monitor LG - SP",
                  "  Teclado Redragon - MG ", "NOTEBOOK Lenovo - RJ", "Webcam Logitech - sp",
                  None, "Monitor Samsung - MG"],
    "preco":     ["R$ 4.200,00", "89,90", "R$ 1.350,00", "210", None,
                  "R$ 149,90", "R$ 99,00", "não informado"],
    "qtd":       ["2", "10", None, "5", "1", "4", "3", "2"],
})
bruto

   pedido                 descricao          preco   qtd
0    1001        Notebook Dell - SP    R$ 4.200,00     2
1    1002       mouse logitech - rj          89,90    10
2    1003           Monitor LG - SP    R$ 1.350,00  None
3    1004    Teclado Redragon - MG             210     5
4    1005      NOTEBOOK Lenovo - RJ           None     1
5    1006      Webcam Logitech - sp      R$ 149,90     4
6    1007                      None       R$ 99,00     3
7    1008      Monitor Samsung - MG  não informado     2

In [ ]:
# verificando tipo da variavel e valor nulos
#bruto.dtypes
bruto.isna().sum()

pedido       0
descricao    1
preco        1
qtd          1
dtype: int64

In [ ]:
# 1. Tira as linhas em que a coluna de texto está vazia.

def remover_sem_descricao(df):
    return df.dropna(subset=["descricao"]).reset_index(drop=True)

passo = remover_sem_descricao(bruto)

In [ ]:
# Chama a funcao
df = remover_sem_descricao(bruto)
df

   pedido                 descricao          preco   qtd
0    1001        Notebook Dell - SP    R$ 4.200,00     2
1    1002       mouse logitech - rj          89,90    10
2    1003           Monitor LG - SP    R$ 1.350,00  None
3    1004    Teclado Redragon - MG             210     5
4    1005      NOTEBOOK Lenovo - RJ           None     1
5    1006      Webcam Logitech - sp      R$ 149,90     4
6    1008      Monitor Samsung - MG  não informado     2

In [ ]:
# 2. Padronizando o texto
""".strip() tira os espaços das pontas"""
""".title() coloca a primeira letra de cada palavra em maiúscula"""

def padronizar_texto(df):
    df = df.copy()
    df["descricao"] = df["descricao"].str.strip().str.title()
    return df

passo = padronizar_texto(passo)

In [ ]:
passo

   pedido              descricao          preco   qtd
0    1001     Notebook Dell - Sp    R$ 4.200,00     2
1    1002    Mouse Logitech - Rj          89,90    10
2    1003        Monitor Lg - Sp    R$ 1.350,00  None
3    1004  Teclado Redragon - Mg            210     5
4    1005   Notebook Lenovo - Rj           None     1
5    1006   Webcam Logitech - Sp      R$ 149,90     4
6    1008   Monitor Samsung - Mg  não informado     2

In [ ]:
# Padronizando texto de uma outra forma
"""
A ideia é separar a descrição no " - ", aplicar .title() só na parte do produto e
.upper() só na parte do estado, e depois juntar de novo."""

def padronizar_texto(df):
    df = df.copy()
    partes = df["descricao"].str.strip().str.split(" - ")
    df["descricao"] = partes.str[0].str.title() + " - " + partes.str[1].str.upper()
    return df

df = padronizar_texto(df)
df

   pedido              descricao          preco   qtd
0    1001     Notebook Dell - SP    R$ 4.200,00     2
1    1002    Mouse Logitech - RJ          89,90    10
2    1003        Monitor Lg - SP    R$ 1.350,00  None
3    1004  Teclado Redragon - MG            210     5
4    1005   Notebook Lenovo - RJ           None     1
5    1006   Webcam Logitech - SP      R$ 149,90     4
6    1008   Monitor Samsung - MG  não informado     2

In [ ]:
# Criando nova coluna (Produto)
"""
.str.split() quebra o texto em uma lista de palavras
.str[0] pega a primeira.
"""

def extrair_produto(df):
    df = df.copy()
    df["produto"] = df["descricao"].str.split().str[0]
    return df

df = extrair_produto(df)

In [ ]:
df

   pedido              descricao          preco   qtd   produto
0    1001     Notebook Dell - SP    R$ 4.200,00     2  Notebook
1    1002    Mouse Logitech - RJ          89,90    10     Mouse
2    1003        Monitor Lg - SP    R$ 1.350,00  None   Monitor
3    1004  Teclado Redragon - MG            210     5   Teclado
4    1005   Notebook Lenovo - RJ           None     1  Notebook
5    1006   Webcam Logitech - SP      R$ 149,90     4    Webcam
6    1008   Monitor Samsung - MG  não informado     2   Monitor

In [ ]:
# Criando nova coluna (marca)
"""
.str.split() quebra o texto em uma lista de palavras
.str[1] pega a segunda palavra, que é a marca
"""

def extrair_marca(df):
    df = df.copy()
    df["marca"] = df["descricao"].str.split().str[1]
    return df

df = extrair_marca(df)

In [ ]:
# Criando nova coluna (estado)
"""
.str.split() quebra o texto em uma lista de palavras
.str[-1] pega a última palavra, que é o estado
.str.upper() deixa tudo em maiúsculas
"""

def extrair_estado(df):
    df = df.copy()
    df["estado"] = df["descricao"].str.split().str[-1].str.upper()
    return df

df = extrair_estado(df)

In [ ]:
# Colocar preco para float

""".str.replace("R$", "", regex=False)	Apaga o símbolo da moeda (troca "R$" por nada)	" 4.200,00"
.str.replace(".", "", regex=False)	Apaga o ponto de milhar	" 4200,00"
.str.replace(",", ".", regex=False)	Troca a vírgula decimal pelo ponto, que é o padrão do Python	" 4200.00"
.str.trip()	Tira os espaços do começo e do fim	"4200.00
to_numeric(df["preco"] - passa a coluna preco para numerico.
errors="coerce" - Vira NaN e a conversão segue
"""

def limpar_preco(df):
    df = df.copy()
    df["preco"] = (df["preco"]
                   .str.replace("R$", "", regex=False)
                   .str.replace(".", "", regex=False)   # tira o ponto de milhar
                   .str.replace(",", ".", regex=False)  # vírgula vira ponto decimal
                   .str.strip())
    df["preco"] = pd.to_numeric(df["preco"], errors="coerce")
    return df

In [ ]:
df = limpar_preco(df)
df

   pedido              descricao   preco   qtd   produto     marca estado
0    1001     Notebook Dell - SP  4200.0     2  Notebook      Dell     SP
1    1002    Mouse Logitech - RJ    89.9    10     Mouse  Logitech     RJ
2    1003        Monitor Lg - SP  1350.0  None   Monitor        Lg     SP
3    1004  Teclado Redragon - MG   210.0     5   Teclado  Redragon     MG
4    1005   Notebook Lenovo - RJ     NaN     1  Notebook    Lenovo     RJ
5    1006   Webcam Logitech - SP   149.9     4    Webcam  Logitech     SP
6    1008   Monitor Samsung - MG     NaN     2   Monitor   Samsung     MG

In [ ]:
# Tratar precos ausentes.

def tratar_preco_ausente(df):
    df = df.copy()
    mediana_produto = df.groupby("produto")["preco"].transform("median")
    df["preco"] = df["preco"].fillna(mediana_produto)
    return df
df = tratar_preco_ausente(df)

In [ ]:
# 8. Converter qtd para inteiro

"""
errors="coerce" - Vira NaN e a conversão segue
fillna(0) - preenche os valores nulos com 0
.astype(int) - converte para inteiro
"""

def tratar_qtd(df):
    df = df.copy()
    df["qtd"] = pd.to_numeric(df["qtd"], errors="coerce").fillna(0).astype(int)
    return df

df = tratar_qtd(df)

In [ ]:
# Calculando total a partir de preco e qtd

def calcular_total(df):
    df = df.copy()
    df["total"] = df.apply(lambda linha: linha["preco"] * linha["qtd"], axis=1)
    return df

df = calcular_total(df)
df

,pedido,descricao,preco,qtd,produto,marca,estado,preco_estimado,total
0,1001,Notebook Dell - SP,4200.0,2,Notebook,Dell,SP,False,8400.0
1,1002,Mouse Logitech - RJ,89.9,10,Mouse,Logitech,RJ,False,899.0
2,1003,Monitor Lg - SP,1350.0,0,Monitor,Lg,SP,False,0.0
3,1004,Teclado Redragon - MG,210.0,5,Teclado,Redragon,MG,False,1050.0
4,1005,Notebook Lenovo - RJ,4200.0,1,Notebook,Lenovo,RJ,True,4200.0
5,1006,Webcam Logitech - SP,149.9,4,Webcam,Logitech,SP,False,599.6
6,1008,Monitor Samsung - MG,1350.0,2,Monitor,Samsung,MG,True,2700.0

In [ ]:
# Criando a coluna frete

df["frete"] = df.apply(
    lambda linha: 0 if linha["total"] > 1000 or linha["estado"] == "SP" else 25,
    axis=1)
df

,pedido,preco,qtd,produto,marca,estado,preco_estimado,total,frete
0,1001,4200.0,2,Notebook,Dell,SP,False,8400.0,0
1,1002,89.9,10,Mouse,Logitech,RJ,False,899.0,25
2,1003,1350.0,0,Monitor,Lg,SP,False,0.0,0
3,1004,210.0,5,Teclado,Redragon,MG,False,1050.0,0
4,1005,4200.0,1,Notebook,Lenovo,RJ,True,4200.0,0
5,1006,149.9,4,Webcam,Logitech,SP,False,599.6,0
6,1008,1350.0,2,Monitor,Samsung,MG,True,2700.0,0

In [ ]:
# Dropando a coluna descricao
def remover_descricao(df):
    df = df.copy()
    df = df.drop(columns="descricao")
    return df

df = remover_descricao(df)
df

   pedido   preco  qtd   produto     marca estado  preco_estimado   total
0    1001  4200.0    2  Notebook      Dell     SP           False  8400.0
1    1002    89.9   10     Mouse  Logitech     RJ           False   899.0
2    1003  1350.0    0   Monitor        Lg     SP           False     0.0
3    1004   210.0    5   Teclado  Redragon     MG           False  1050.0
4    1005  4200.0    1  Notebook    Lenovo     RJ            True  4200.0
5    1006   149.9    4    Webcam  Logitech     SP           False   599.6
6    1008  1350.0    2   Monitor   Samsung     MG            True  2700.0

# Exercícios/Atividades

1. remova os anúncios vazios.
2. padronizar_anuncio(df): tire os espaços sobrando e padronize as maiúsculas.
3. extrair_tipo(df): crie a coluna tipo (Apartamento, Casa, Studio).
4. extrair_quartos(df): crie a coluna quartos como número inteiro.
5. extrair_bairro(df): crie a coluna bairro
6. limpar_moeda(df, coluna): converta uma coluna de dinheiro para float.
7. limpar_area(df): converta area para float, removendo o m².
8. tratar_ausentes(df), com estas regras de negócio.
9. calcular_indicadores(df): crie custo_mensal (aluguel + condomínio) e preco_m2 (aluguel ÷ área, com 2 casas decimais)

In [ ]:
import pandas as pd
import numpy as np

imoveis = pd.DataFrame({
    "codigo": [501, 502, 503, 504, 505, 506, 507, 508],
    "anuncio": ["Apartamento - 2 quartos - Moema",
                "casa - 3 QUARTOS - pinheiros",
                "  Studio - 1 quarto - Vila Madalena ",
                "APARTAMENTO - 3 quartos - Moema",
                "Casa - 4 quartos - Butantã",
                None,
                "apartamento - 2 quartos - pinheiros",
                "Studio - 1 quarto - Bela Vista"],
    "aluguel": ["R$ 3.500,00", "2.800", "R$ 2.100,00", "R$ 5.200,00",
                None, "R$ 1.900,00", "R$ 3.100,00", "sob consulta"],
    "area": ["65 m²", "120m²", "32 m²", None, "180 m²", "50 m²", "70 m²", "35m²"],
    "condominio": ["R$ 850,00", None, "R$ 450,00", "R$ 1.200,00",
                   None, "R$ 600,00", "R$ 700,00", "R$ 380,00"],
})
imoveis

,codigo,anuncio,aluguel,area,condominio
0,501,Apartamento - 2 quartos - Moema,"R$ 3.500,00",65 m²,"R$ 850,00"
1,502,casa - 3 QUARTOS - pinheiros,2.800,120m²,None
2,503,Studio - 1 quarto - Vila Madalena,"R$ 2.100,00",32 m²,"R$ 450,00"
3,504,APARTAMENTO - 3 quartos - Moema,"R$ 5.200,00",None,"R$ 1.200,00"
4,505,Casa - 4 quartos - Butantã,None,180 m²,None
5,506,None,"R$ 1.900,00",50 m²,"R$ 600,00"
6,507,apartamento - 2 quartos - pinheiros,"R$ 3.100,00",70 m²,"R$ 700,00"
7,508,Studio - 1 quarto - Bela Vista,sob consulta,35m²,"R$ 380,00"